export interface Empresa {
  id: number;
  nomeFantasia: string;
  razaoSocial: string;
  dataConstituicao: string;
  cnpj: string;
  inscricaoEstadual: string;
  inscricaoMunicipal: string;
  regimeTributario: string;
  cep: number;
  endereco: string;
  numero: string;
  complemento: string;
  bairro: string;
  municipio: string;
  estado: string;
  ramoDeAtividade: string;
  telefone: string;
  telefone2: string;
  whatsapp: string;
  celular: string;
  email: string;
  website: string;
  redeSocial: string;
  redeSocial2: string;
  redeSocial3: string;
  dataCadastro: string;
  statusEmpresa: string;
}
